### ISSUE TITLE
Login Constantly Fails

### ISSUE THREAD

**Issue by n0pe-sled** [DeeZem/Superchillin.bundle#5]
The channel cannot log in correctly anymore.

**Comment by Pharrcyde** [comment]
Same here. Once I updated the Plex Server I started having this issue.

**Comment by Pharrcyde** [comment]
This issue still occured on the previous version (Jul 9, 2016) of the channel after the plex update btw.

**Comment by DeeZem** [comment]
The login failure is caused by the captcha now being required for every login on the site. Try going to your user settings on the website and checking the box for "Ignore Login Page Captcha Requirement".

If that doesn't work, I committed a change last night that should allow you to input the cookie variables in the Plex channel preferences to bypass the login process. You'll just need to copy the data out of your browser's cookie for the site.

**Comment by Pharrcyde** [comment]
Yeah Just found out about it and was about to post about it here. Found the "Ignore Login Page Captcha Requirement" setting a few min ago, lol.
Testing it.

**Comment by Pharrcyde** [comment]
Still having the issue, I'll try the cookie variables and see if that works.

**Comment by Pharrcyde** [comment]
It worked perfectly using the cookie variables. I guess its safer than disabling the captcha setting anyways.

**Comment by n0pe-sled** [comment]
Sorry I didnt realize that you updated the code base.  Once I pulled down the changes it worked with the noob and auth code!  Thanks

**Comment by DeeZem** [comment]
Glad the cookie method worked for you guys. I don't like that it's not user friendly, but it seems like the most secure way since the site can still have the captcha and the cookie can be easily revoked if stolen (just log out of that session).

I'm open to listen to any suggestions of ways to improve the channel (especially the login process), but since this worked for both of you I'm going to close this issue.
